"""empty message

Revision ID: 1f373cec4eae
Revises: ca4a5853e61f
Create Date: 2022-04-07 11:18:19.858339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f373cec4eae'
down_revision = 'ca4a5853e61f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_details', sa.Column('det_qty', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_details', 'det_qty')
    # ### end Alembic commands ###
